== Short Intro to the Nano Editor

If you don't like *Vim* feel free to use *Nano*, a simple to use command line editor. Here is a short intro to get you started.

=== Basic Commands

TIP: *Ctrl-<n>* or *Alt-<n>* means press and holt the Control or Alt key and then press the character after the dash. 

To create a new file or open an existing file:
----
[ansible@control ~]$ nano playbook.yml
----

TIP: When Nano asks for confirmation, it expects a *y* for yes or *n* for no.  

To save the current file in Nano:

----
Ctrl-o y Enter
----

To leave Nano without saving the file (if something went wrong while editing and you just want out without changing anything):
----
Ctrl-x n Enter
----

Copy and paste: To mark the begin of the text to copy
----
Alt-a
----

The use the cursor arrow keys to mark the text. Copy the text with:
----
Alt-6
----

Move the cursor to the position where you want it and paste:
----
Ctrl-u
----

=== Show Whitespaces

Ansible uses YAML so it comes in handy to mark whitespaces from time to time. In Nano just press *Alt-p* to toggle whitespaces.

For the full documentation go https://www.nano-editor.org/dist/v3/nano.html[here] or use the man page.

=== Syntax Highlighting

WARNING: This will not work for older Nano version (like in RHEL 7).

To enable syntax highlighting for YAML files:
----
[ansible@control ~]$ mkdir -p ~/.nano/syntax
----

Create the file `~/.nano/syntax/yaml.nanorc` with the following content:
----
# Supports `YAML` files
syntax "YAML" "\.ya?ml$"
header "^(---|===)" "%YAML"

## Keys
color magenta "^\s*[\$A-Za-z0-9_-]+\:"
color brightmagenta "^\s*@[\$A-Za-z0-9_-]+\:"

## Values
color white ":\s.+$"
## Booleans
icolor brightcyan " (y|yes|n|no|true|false|on|off)$"
## Numbers
color brightred " [[:digit:]]+(\.[[:digit:]]+)?"
## Arrays
color red "\[" "\]" ":\s+[|>]" "^\s*- "
## Reserved
color green "(^| )!!(binary|bool|float|int|map|null|omap|seq|set|str) "

## Comments
color brightwhite "#.*$"

## Errors
color ,red ":\w.+$"
color ,red ":'.+$"
color ,red ":".+$"
color ,red "\s+$"

## Non closed quote
color ,red "['\"][^['\"]]*$"

## Closed quotes
color yellow "['\"].*['\"]"

## Equal sign
color brightgreen ":( |$)"
----

To load the definition create the file `~/.nanorc` with the following content:
----
include ~/.nano/syntax/yaml.nanorc
include /usr/share/nano/*
----

TIP: This `.nanorc` will enable YAML and all other syntax highlighting coming with Nano.


