== Editor Alternatives

If you don't like *Vim* as an editor feel free to use *Nano* or *Midnight Commander* (*mc*) in the SSH terminal. Here is a quick introduction to both. And no, I'll refuse to talk about Emacs... ;-)

=== Midnight Commander (mc)

Mc is more then an editor, it's a file manager. And it has this nice nineties feel about it... anyway we'll focus on editing files here.

To open *mc* at the commandline prompt type:

----
# mc
----

==== Basic Editing

Mc is controlled mainly through the function keys. This can pose all kinds of issues when run in a terminal session, e.g. *F10* is most times caught as a shortcut by the terminal window.

To work around this:

* Try the "Windows" key: *Win + F10* to get *F10*
* Use the mouse, all *mc* keys should be clickable, even if they don't look it.

To create a new file:

* Type `touch filename` in the command field to create an empty file
* Navigate with the *arrow keys* in one of the panes to the new file
* Hit (or click) *F4* to start editing the file

To save a file:

* Hit (or click) *F2* and confirm with *Enter*

To exit edit mode with or without saving:

* Hit *Win-Key + F10* or click *F10*
* If you did any changes you will be asked "Save before Close?". 
* Choose one of the options "Yes, No, Cancel" by moving with the *arrow* or *Tab* keys (or click) 

Copy text:

* Position the cursor where you want to start to copy
* Hit (or click) *F3* to start selecting
* Move the cursor to highlight/select the text you want to copy
* Hit (or click) *F3* again to stop selecting

Paste text:

* Position the cursor where you want to paste the text
* Hit (or click) *F5* to paste a copy of the text
* Hit (or select) *F6* to cut the text and paste it here

=== Short Intro to the Nano Editor

If you don't like *Vim* and you feel too young for *Midnight Commander* use *Nano*, a simple to use command line editor. 

==== Basic Commands

TIP: *Ctrl-<n>* or *Alt-<n>* means press and hold the Control or Alt key and then press the character after the dash. 

To create a new file or open an existing file:
----
# nano playbook.yml
----

TIP: When Nano asks for confirmation, it expects a *y* for yes or *n* for no.  

To save the current file in Nano:
----
Ctrl-o
----

TIP: Depending if the file was changed or not Nano will ask for confirmation and the file name.

To leave Nano without saving the file (if something went wrong while editing and you just want out without changing anything):
----
Ctrl-x n Enter
----

Copy and paste: 

To mark the begin of the text to copy
----
Alt-a
----

The use the cursor arrow keys to mark the text. Copy the text with:
----
Alt-6
----

Move the cursor to the position where you want it and paste:
----
Ctrl-u
----

####### Stuff below this line is meant for documenting only, don't put in a lab gude w/o testing!!!!! 

==== Show Whitespaces

Ansible uses YAML so it comes in handy to mark whitespaces (or reveal *tabs* ;-). 

* First use Nano to create a _.nanorc_ file in your home directory so it looks like this:
----
set whitespace "»·"
----

* To toggle *tab* and *whitespace* display in Nano just press *Alt-p*.

==== More Help

For the full documentation for Nano 2 (included in RHEL 7) go https://www.nano-editor.org/dist/v2.2/nano.html[here], for the recent version 3 go here https://www.nano-editor.org/dist/v3/nano.html[here] or use the man page.

==== Syntax Highlighting

WARNING: This will not work for older Nano version (like in RHEL 7).

To enable syntax highlighting for YAML files:
----
[ansible@control ~]$ mkdir -p ~/.nano/syntax
----

Create the file `~/.nano/syntax/yaml.nanorc` with the following content:
----
# Supports `YAML` files
syntax "YAML" "\.ya?ml$"
header "^(---|===)" "%YAML"

## Keys
color magenta "^\s*[\$A-Za-z0-9_-]+\:"
color brightmagenta "^\s*@[\$A-Za-z0-9_-]+\:"

## Values
color white ":\s.+$"
## Booleans
icolor brightcyan " (y|yes|n|no|true|false|on|off)$"
## Numbers
color brightred " [[:digit:]]+(\.[[:digit:]]+)?"
## Arrays
color red "\[" "\]" ":\s+[|>]" "^\s*- "
## Reserved
color green "(^| )!!(binary|bool|float|int|map|null|omap|seq|set|str) "

## Comments
color brightwhite "#.*$"

## Errors
color ,red ":\w.+$"
color ,red ":'.+$"
color ,red ":".+$"
color ,red "\s+$"

## Non closed quote
color ,red "['\"][^['\"]]*$"

## Closed quotes
color yellow "['\"].*['\"]"

## Equal sign
color brightgreen ":( |$)"
----

To load the definition create the file `~/.nanorc` with the following content:
----
include ~/.nano/syntax/yaml.nanorc
include /usr/share/nano/*
----

TIP: This `.nanorc` will enable YAML and all other syntax highlighting coming with Nano.


