= Style guide for trainings in this repository

Our style guidelines ensure that all labs follow a consistent layout - and make it easier for contributors to edit and improve the labs.

== Headers

Headers are marke with equal signs:

----
= Document Title (Level 0)

== Level 1 Section Title

=== Level 2 Section Title
----

== Formatted text, highlights, etc.

Text will be standard formatted (no italics, no bold, etc.), except for the following situations.

=== Code, addresses, host names, everything for copy & paste

Every piece of text which in theory can be copied and pasted during the lab, is marked as `code` with upper tics:

----
`curl https://www.redhat.com`
`admin@example.com`
----

=== Visual elements

In these labs the users often have to interact with UIs, and thus pieces of the UI need to be recognized. Such elements are marked *bold* and are spelled and written exactly the same way they are in the UI. For example, if the lab requires that you  click on the tab called projects, written in all capital letters, the lab guide would refer to it as *PROJECTS*.

----
Click on *INVENTORY* and afterwards note the *TYPE* column with the key word *Inventory*.
----

== Final words

If you find a piece in the labs which does not follow the style guideline, we are happy if you let us know via an issue - or a PR.
